version: '3.9'

services:

  nginx:
    container_name: nginx
    image: nginx:1.22-alpine
    ports:
      - 80:80
    # Reference link for the code used in the command
    # https://stackoverflow.com/questions/56960355/docker-compose-throws-adduser-group-www-data-in-use
    command: "&& mkdir -p /var/www/wordpress && adduser -D -H -u 1000 -s /bin/bash www-data -G www-data && && chown -R www-data:www-data /var/www/wordpress"
    volumes:
      - ./nginx-custom-configs/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/wordpress:delegated
    networks:
      - wordpress-dev-network
    depends_on:
      - php
  
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /var/opt/mysql/wp-local-data:/var/lib/mysql:delegated
    networks:
      - wordpress-dev-network
  
  php:
    container_name: php
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/wordpress:delegated
    networks:
      - wordpress-dev-network
    depends_on:
      - mysql

networks:
  wordpress-dev-network: