version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/wordpress:delegated
    networks:
      - wordpress-dev-network
    depends_on:
      - php
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /var/opt/mysql/wp-local-data:/var/lib/mysql
    networks:
      - wordpress-dev-network
  php:
    container_name: php
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/wordpress:delegated
    networks:
      - wordpress-dev-network
    depends_on:
      - mysql

networks:
  wordpress-dev-network: